name: WakaTime Total Time Card

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-wakatime-card:
    name: Generate and commit WakaTime Total Time Card
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: master-chief/waka-time-card@v1.4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          CARD_TYPE: 'total'
          TIME_FORMAT: 'human_readable'
          FILE_NAME: 'waka-total-time-card.svg'
          TEXT_COLOR: 'ffffff'
          TITLE_COLOR: 'ffffff'
          ICON_COLOR: 'E3508C'
          BACKGROUND_COLOR: '0D1117'
          BORDER_COLOR: '0D1117'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update WakaTime Total Time Card
          files: 'waka-total-time-card.svg'
